export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  DISCORD_CALLBACK: "/auth/discord/callback",
  PLAYER_PROFILE: "/player/:id",
  EMAIL_VERIFY: "/verify-email",
  SUPER_ADMIN: "/super-admin/:id",
  CREATE_ORG: "/create-org",
  NOTIFICATIONS: "/notifications",
  ALL_PLAYERS: "/players",
  ALL_TEAMS: "/teams",

  ORG_PROFILE: "/organizer/:id",
  ORG_DASHBOARD: "/organizer-dashboard/:id",

  ALL_EVENTS: "/tournaments",
  EVENT_DETAILS: "/organizer/event/:eventId",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  TRENDING: "/trending",
  COMMUNITY: "/community",
  UPGRADE: "/upgrade",
};
