export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  DISCORD_CALLBACK: "/auth/discord/callback",
  PROFILE: "/profile",
  ORG_PROFILE: "/org-profile/:id",
  EMAIL_VERIFY: "/verify-account",
  TEAM_PROFILE: "/team-profile",
  ORG_DASHBOARD: "/organizer",
  SUPER_ADMIN: "/super-admin",
  CREATE_ORG: "/create-org",
  TEAM_DASHBOARD: "/team/:teamId/dashboard",
};

// export const ROUTES = {
//   PROFILE: "/profile",
//   USERPROFILE: "/profile/:id",
//   CREATE_TEAM: "/create-team",
//   TEAMPROFILE: "/team-profile",
//   USERTEAMPROFILE: "/team-profile/:id",
//   EVENTS: "/events", // /events/:type
//   EVENT: "/events/:id",
//   FREE_TOURNAMENTS: "/free-tournaments",
//   BLOG: "/blog",
//   BLOG_POST: "/blog/:id",
//   SCRIMSPAGE: "/scrims",
//   TEAMS: "/teams",
//   ADMIN: "/admin/dashboard",
//   MAXADMIN: "/admin/super",
//   NOTIFICATION: "/notifications",
//   PLAYER: "/players",
//   NOTFOUND: "/*",
//   ORGANIZER_DASHBOARD: "/dashboard/*",
// };
