import { Team } from "./team";

export const teams: Team[] = [
  {
    id: "1",
    name: "Phoenix Elite",
    region: "Asia",
    rank: "Diamond",
    members: [
      {
        id: "m1",
        name: "DragonSlayer",
        role: "Leader",
        rank: "Diamond I",
        level: 75,
        avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857",
      },
      {
        id: "m2",
        name: "ShadowHunter",
        role: "Support",
        rank: "Platinum II",
        level: 60,
        avatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
      },
    ],
    recruitingRoles: ["Rusher", "Sniper"],
    requirements: {
      minLevel: 50,
      minRank: "Platinum",
      preferredRoles: ["Support", "Rusher"],
    },
    active: true,
    lastActive: "2024-03-10T15:30:00Z",
  },
  {
    id: "2",
    name: "Shadow Wolves",
    region: "Europe",
    rank: "Platinum",
    members: [
      {
        id: "m1",
        name: "NightFury",
        role: "Leader",
        rank: "Platinum I",
        level: 68,
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
      },
      {
        id: "m2",
        name: "IceArrow",
        role: "Sniper",
        rank: "Gold III",
        level: 52,
        avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
      },
    ],
    recruitingRoles: ["Support"],
    requirements: {
      minLevel: 40,
      minRank: "Gold",
      preferredRoles: ["Sniper", "Rusher"],
    },
    active: false,
    lastActive: "2024-01-22T10:15:00Z",
  },
  {
    id: "3",
    name: "Blaze Titans",
    region: "North America",
    rank: "Diamond",
    members: [
      {
        id: "m1",
        name: "FireLord",
        role: "Leader",
        rank: "Diamond II",
        level: 80,
        avatar: "https://images.unsplash.com/photo-1517702228291-3b5823c26250",
      },
    ],
    recruitingRoles: ["Sniper", "Strategist"],
    requirements: {
      minLevel: 60,
      minRank: "Diamond",
      preferredRoles: ["Sniper", "Support"],
    },
    active: true,
    lastActive: "2024-03-01T13:00:00Z",
  },
  {
    id: "4",
    name: "Iron Giants",
    region: "South America",
    rank: "Gold",
    members: [
      {
        id: "m1",
        name: "MetalHead",
        role: "Leader",
        rank: "Gold II",
        level: 45,
        avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df",
      },
    ],
    recruitingRoles: ["Tank", "Support"],
    requirements: {
      minLevel: 30,
      minRank: "Gold",
      preferredRoles: ["Tank"],
    },
    active: true,
    lastActive: "2024-02-15T18:00:00Z",
  },
  {
    id: "5",
    name: "StormBreakers",
    region: "Asia",
    rank: "Diamond",
    members: [
      {
        id: "m1",
        name: "LightningBolt",
        role: "Leader",
        rank: "Diamond I",
        level: 72,
        avatar: "https://images.unsplash.com/photo-1548964095-6aee63c57ef5",
      },
      {
        id: "m2",
        name: "ThunderClap",
        role: "Support",
        rank: "Platinum III",
        level: 55,
        avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df",
      },
    ],
    recruitingRoles: ["Support"],
    requirements: {
      minLevel: 50,
      minRank: "Platinum",
      preferredRoles: ["Support", "Sniper"],
    },
    active: true,
    lastActive: "2024-03-11T08:30:00Z",
  },
  {
    id: "6",
    name: "Frozen Fury",
    region: "Europe",
    rank: "Gold",
    members: [
      {
        id: "m1",
        name: "IceBreaker",
        role: "Leader",
        rank: "Gold II",
        level: 62,
        avatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79",
      },
    ],
    recruitingRoles: ["Sniper"],
    requirements: {
      minLevel: 40,
      minRank: "Gold",
      preferredRoles: ["Sniper", "Rusher"],
    },
    active: false,
    lastActive: "2024-02-28T17:00:00Z",
  },
  {
    id: "7",
    name: "Eclipse Squad",
    region: "North America",
    rank: "Diamond",
    members: [
      {
        id: "m1",
        name: "ShadowMaster",
        role: "Leader",
        rank: "Diamond III",
        level: 78,
        avatar: "https://images.unsplash.com/photo-1562007907-05c48dc9ee5a",
      },
    ],
    recruitingRoles: ["Rusher"],
    requirements: {
      minLevel: 60,
      minRank: "Diamond",
      preferredRoles: ["Rusher"],
    },
    active: true,
    lastActive: "2024-03-03T09:30:00Z",
  },
  {
    id: "8",
    name: "Night Hawks",
    region: "Asia",
    rank: "Platinum",
    members: [
      {
        id: "m1",
        name: "DarkWing",
        role: "Leader",
        rank: "Platinum III",
        level: 69,
        avatar: "https://images.unsplash.com/photo-1529021222774-5fea6d15b311",
      },
    ],
    recruitingRoles: ["Support"],
    requirements: {
      minLevel: 40,
      minRank: "Gold",
      preferredRoles: ["Support", "Sniper"],
    },
    active: true,
    lastActive: "2024-03-05T12:00:00Z",
  },
  {
    id: "9",
    name: "Thunder Wolves",
    region: "South America",
    rank: "Platinum",
    members: [
      {
        id: "m1",
        name: "StormWolf",
        role: "Leader",
        rank: "Platinum II",
        level: 64,
        avatar: "https://images.unsplash.com/photo-1511734032410-4b060b9d9e0c",
      },
    ],
    recruitingRoles: ["Sniper", "Strategist"],
    requirements: {
      minLevel: 45,
      minRank: "Gold",
      preferredRoles: ["Strategist", "Sniper"],
    },
    active: true,
    lastActive: "2024-03-07T16:45:00Z",
  },
  {
    id: "10",
    name: "Crimson Blades",
    region: "Europe",
    rank: "Gold",
    members: [
      {
        id: "m1",
        name: "CrimsonKing",
        role: "Leader",
        rank: "Gold III",
        level: 50,
        avatar: "https://images.unsplash.com/photo-1564564295391-7f24f26f568b",
      },
    ],
    recruitingRoles: ["Support"],
    requirements: {
      minLevel: 30,
      minRank: "Gold",
      preferredRoles: ["Support"],
    },
    active: false,
    lastActive: "2024-02-14T20:00:00Z",
  },
];
